backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "about"
    label: "Про нас"
    folder: "content/about"
    create: false
    slug: "index"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Основний текст", name: "body", widget: "markdown" }
      - label: "Галерея фото"
        name: "images"
        widget: "list"
        field:
          label: "Фото"
          name: "image"
          widget: "image"
      - label: "Відео"
        name: "video"
        widget: "file"
        required: false
        allow_multiple: false

  -   - name: "services"
        label: "Види послуг"
        folder: "content/services/"
        create: true
        slug: "{{title}}"
        fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Превʼю", name: "preview", widget: "image" }
      - label: "Галерея"
        name: "gallery"
        widget: "list"
        field:
          label: "Фото"
          name: "image"
          widget: "image"
      - { label: "Відео", name: "video", widget: "file" }
      - { label: "Прайс", name: "price", widget: "markdown" }
      - { label: "Опис", name: "body", widget: "markdown" }


  - name: "portfolio"
    label: "Портфоліо"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Фото", name: "image", widget: "image" }
